title: OpenGridMap
include: ['_pages']
ga_tracking_id: UA-63269373-1

primary-nav-items:
    - label: About Open Grid Map
      url: /

    - label: Map
      url: http://vmjacobsen39.informatik.tu-muenchen.de/

    - label: App
      url: https://play.google.com/store/apps/details?id=tanuj.opengridmap

    - label: Press
      url: /press/

    - label: Impressum
      url: /impressum/

    - label: Terms Of Use
      url: /terms/
